services:
  gophermart:
    depends_on:
      - db
    build: .
    ports:
      - '8082:8080'
    environment:
      DATABASE_URI: 'postgres://postgres:123@db:5432/postgres'
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  db:
    driver: local
